// Renders deck.html to pitch/out/tripai-pitch-{en,pl}.pdf plus PNG previews of every slide.
// Usage: node build.mjs [en|pl]   (screenshots first: node shots.mjs)
import { chromium } from 'playwright';
import QRCode from 'qrcode';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT0 = path.resolve(HERE, '../out');
// The app URL (QR + text on slide 10) is never committed: the repo is public.
// Without TRIPAI_APP_URL the build renders placeholders into out/ (the committed copy);
// with it, the real decks go to out/private/ (gitignored) for presenting.
const APP = process.env.TRIPAI_APP_URL?.replace(/\/$/, '');
const PUBLIC = !APP;
const langs = process.argv[2] ? [process.argv[2]] : ['en', 'pl'];

// screenshot metadata (crop rects, scan gate) for the page
const metaJson = path.join(HERE, 'shots', 'meta.json');
const meta = fs.existsSync(metaJson) ? fs.readFileSync(metaJson, 'utf8') : '{}';
fs.writeFileSync(path.join(HERE, 'shots', 'meta.js'), `// generated by build.mjs from shots/meta.json\nwindow.SHOT_META = ${meta.trim()};\n`);

const OUT = PUBLIC ? OUT0 : path.join(OUT0, 'private');
const svg = PUBLIC ? null : await QRCode.toString(APP, { type: 'svg', margin: 0, errorCorrectionLevel: 'M', color: { dark: '#111111', light: '#ffffff' } });
fs.writeFileSync(
  path.join(HERE, 'qr.js'),
  PUBLIC
    ? '// generated by build.mjs (public build: no app URL)\nwindow.DECK_QR = null;\nwindow.DECK_URL = "[app URL]";\n'
    : `// generated by build.mjs\nwindow.DECK_QR = ${JSON.stringify(svg)};\nwindow.DECK_URL = ${JSON.stringify(new URL(APP).host)};\nwindow.DECK_HREF = ${JSON.stringify(APP + '/')};\n`,
);

fs.mkdirSync(path.join(OUT, 'preview'), { recursive: true });
const browser = await chromium.launch();
for (const lang of langs) {
  const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  const errors = [];
  page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto(`${pathToFileURL(path.join(HERE, 'deck.html')).href}?lang=${lang}`, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  const broken = await page.evaluate(() => [...document.images].filter((i) => !i.complete || !i.naturalWidth).map((i) => i.src));
  if (broken.length) errors.push('broken images: ' + broken.join(', '));
  // overflow check: any element sticking out of its slide
  const overflow = await page.evaluate(() =>
    [...document.querySelectorAll('.slide')].flatMap((s, i) => {
      const r = s.getBoundingClientRect();
      return [...s.querySelectorAll('*')]
        .filter((e) => { const b = e.getBoundingClientRect(); return b.width && !e.closest('.bleed') && (b.right > r.right + 1 || b.bottom > r.bottom + 1); })
        .slice(0, 3).map((e) => `slide ${i + 1}: <${e.tagName.toLowerCase()} class="${e.className.baseVal ?? e.className}">`);
    }));
  if (overflow.length) console.warn(`[${lang}] overflow:\n  ` + overflow.join('\n  '));
  if (errors.length) { console.error(`[${lang}] errors:\n  ` + errors.join('\n  ')); process.exitCode = 1; }

  const slides = page.locator('.slide');
  const n = await slides.count();
  for (let i = 0; i < n; i++) {
    await slides.nth(i).screenshot({ path: path.join(OUT, 'preview', `${lang}-${String(i + 1).padStart(2, '0')}.png`) });
  }
  await page.pdf({ path: path.join(OUT, `tripai-pitch-${lang}.pdf`), width: '1920px', height: '1080px', printBackground: true, preferCSSPageSize: true });
  console.log(`${lang}: ${n} slides -> out/tripai-pitch-${lang}.pdf`);
  await page.close();
}
await browser.close();
