// generated by build.mjs from shots/meta.json
window.SHOT_META = {
  "en": {
    "receiptCard": {
      "x": 36,
      "y": 268,
      "w": 318,
      "h": 249
    },
    "inboxGate": {
      "push": false,
      "p": null
    },
    "scan": {
      "windows": 16,
      "candidates": 34
    },
    "capturedAt": "2026-10-04T07:15:16.478Z"
  },
  "pl": {
    "receiptCard": {
      "x": 36,
      "y": 268,
      "w": 318,
      "h": 249
    },
    "inboxGate": {
      "push": false,
      "p": null
    },
    "scan": {
      "windows": 16,
      "candidates": 34
    },
    "capturedAt": "2026-10-04T07:15:15.303Z"
  }
};
