// generated by build.mjs from shots/meta.json
window.SHOT_META = {
  "en": {
    "top": "Catania, 7–11 Nov, ~1,550 PLN · estimate",
    "receiptCard": {
      "x": 36,
      "y": 294,
      "w": 318,
      "h": 249
    },
    "inboxGate": {
      "push": false,
      "p": null
    },
    "scan": {
      "windows": 16,
      "candidates": 34
    },
    "capturedAt": "2026-10-04T05:21:54.468Z"
  },
  "pl": {
    "top": "Catania, 7–11 lis, ~1 550 zł · szacunek",
    "receiptCard": {
      "x": 36,
      "y": 294,
      "w": 318,
      "h": 249
    },
    "inboxGate": {
      "push": false,
      "p": 0.6
    },
    "scan": {
      "windows": 16,
      "candidates": 34
    },
    "capturedAt": "2026-10-04T05:21:59.435Z"
  }
};
